const resObj = {
  cards: [
    {
      id: "1",
      name: "Meghana Foods",
      cloudinaryImageId: "aqsnrylokzpn45qhg1pb",
      areaName: "Koramangala",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Andhra"],
      avgRating: 4.4,
      sla: { deliveryTime: 25, slaString: "20-30 mins" },
      isOpen: true,
    },
    {
      id: "2",
      name: "Empire Restaurant",
      cloudinaryImageId: "w7zxfwyq5n2p7nr6j7rl",
      areaName: "Church Street",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "North Indian"],
      avgRating: 4.2,
      sla: { deliveryTime: 30, slaString: "25-35 mins" },
      isOpen: true,
    },
    {
      id: "3",
      name: "Truffles",
      cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
      areaName: "Koramangala",
      costForTwo: "₹600 for two",
      cuisines: ["American", "Burgers"],
      avgRating: 4.5,
      sla: { deliveryTime: 28, slaString: "25-30 mins" },
      isOpen: true,
    },
    {
      id: "4",
      name: "Burger King",
      cloudinaryImageId: "ufzxqfkutlwd0nnbbc5v",
      areaName: "BTM Layout",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "Fast Food"],
      avgRating: 4.1,
      sla: { deliveryTime: 20, slaString: "18-25 mins" },
      isOpen: true,
    },
    {
      id: "5",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      areaName: "HSR Layout",
      costForTwo: "₹450 for two",
      cuisines: ["Fast Food", "Fried Chicken"],
      avgRating: 4.0,
      sla: { deliveryTime: 22, slaString: "20-25 mins" },
      isOpen: true,
    },
    {
      id: "6",
      name: "California Burrito",
      cloudinaryImageId: "lnego5raqp4lgokolgei",
      areaName: "Indiranagar",
      costForTwo: "₹350 for two",
      cuisines: ["Mexican", "Healthy"],
      avgRating: 4.6,
      sla: { deliveryTime: 26, slaString: "24-30 mins" },
      isOpen: true,
    },
    {
      id: "7",
      name: "A2B - Adyar Ananda Bhavan",
      cloudinaryImageId: "juzk5ecm9jbkz7obmvvv",
      areaName: "BTM",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "Veg"],
      avgRating: 4.3,
      sla: { deliveryTime: 18, slaString: "15-20 mins" },
      isOpen: true,
    },
    {
      id: "8",
      name: "Beijing Bites",
      cloudinaryImageId: "ibx2lnm3jeyt4hmyyiiu",
      areaName: "Marathahalli",
      costForTwo: "₹350 for two",
      cuisines: ["Chinese", "Thai"],
      avgRating: 4.1,
      sla: { deliveryTime: 32, slaString: "30-35 mins" },
      isOpen: true,
    },
    {
      id: "9",
      name: "Chai Point",
      cloudinaryImageId: "dr9bkle5jkbtmnp8jo7e",
      areaName: "Whitefield",
      costForTwo: "₹150 for two",
      cuisines: ["Tea", "Snacks"],
      avgRating: 4.2,
      sla: { deliveryTime: 20, slaString: "18-22 mins" },
      isOpen: true,
    },
    {
      id: "10",
      name: "Domino’s Pizza",
      cloudinaryImageId: "rxk4gvzjv9c5p7x8ptfh",
      areaName: "Koramangala",
      costForTwo: "₹400 for two",
      cuisines: ["Pizza", "Italian"],
      avgRating: 4.0,
      sla: { deliveryTime: 25, slaString: "20-30 mins" },
      isOpen: true,
    },
  ],
};

export default resObj;
